const API_BASE_URL=localStorage.getItem("farmDirectApiBase")||"http://127.0.0.1:8000";
function getToken(){return localStorage.getItem("farmDirectToken")||"";}
function getUser(){try{return JSON.parse(localStorage.getItem("farmDirectUser")||"null");}catch(e){return null;}}
function setAuthSession(data){if(data?.access_token)localStorage.setItem("farmDirectToken",data.access_token);if(data?.user)localStorage.setItem("farmDirectUser",JSON.stringify(data.user));}
function clearAuthSession(){localStorage.removeItem("farmDirectToken");localStorage.removeItem("farmDirectUser");}
function authHeaders(extra={}){const h={...extra};const token=getToken();if(token)h.Authorization=`Bearer ${token}`;return h;}
function apiUrl(endpoint){if(/^https?:\/\//i.test(endpoint))return endpoint;let path=endpoint.startsWith("/")?endpoint:`/${endpoint}`;if(!path.startsWith("/api/"))path="/api"+path;return API_BASE_URL+path;}
async function apiRequest(endpoint,options={}){const {method="GET",body=null,query=null,headers={}}=options;const url=new URL(apiUrl(endpoint));if(query)Object.entries(query).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")url.searchParams.set(k,String(v));});const finalHeaders=authHeaders({...headers});let finalBody=body;if(body!==null&&body!==undefined&&!(body instanceof FormData)){finalHeaders["Content-Type"]=finalHeaders["Content-Type"]||"application/json";finalBody=JSON.stringify(body);}let response;try{response=await fetch(url.toString(),{method,headers:finalHeaders,body:finalBody});}catch(e){throw new Error("Farmova service is unavailable right now. Please start the Farmova backend and try again.");}let data={};try{data=await response.json();}catch(e){}if(response.status===401){clearAuthSession();if(!location.pathname.endsWith("login.html"))location.href="login.html?next="+encodeURIComponent(location.pathname.split("/").pop()||"index.html");throw new Error(data.detail||"Your Farmova session has expired. Please log in again.");}if(!response.ok){const msg=Array.isArray(data.detail)?data.detail.map(x=>x?.msg||x).join(", "):(data.detail||data.message||`Farmova could not complete the request (${response.status}).`);throw new Error(msg);}return data;}
async function apiGet(endpoint,query=null){return apiRequest(endpoint,{query});}
async function apiPost(endpoint,body=null,query=null){return apiRequest(endpoint,{method:"POST",body,query});}
async function apiPut(endpoint,body=null,query=null){return apiRequest(endpoint,{method:"PUT",body,query});}
async function apiDelete(endpoint,query=null){return apiRequest(endpoint,{method:"DELETE",query});}
