let allProduce=[],filteredProduce=[],selectedProduce=null;
document.addEventListener("DOMContentLoaded",function(){
const user=getUser();
if(!user||user.role!=="BUYER"){if(!user){location.href="login.html?next=buyer-dashboard.html";}return;}
document.getElementById("searchInput")?.addEventListener("input",applyFilters);
document.getElementById("locationSelect")?.addEventListener("change",applyFilters);
document.getElementById("sortSelect")?.addEventListener("change",applyFilters);
document.getElementById("offerForm")?.addEventListener("submit",submitOffer);
document.getElementById("closeDetailsBtn")?.addEventListener("click",closeDetailsModal);
document.getElementById("closeOfferBtn")?.addEventListener("click",closeOfferModal);
loadVoiceSearch();
fetchMarketplaceItems();
});
async function fetchMarketplaceItems(){const grid=document.getElementById("marketplaceGrid");try{grid.innerHTML='<div class="col-span-full text-center py-12 text-slate-400 text-sm">Loading live crop listings...</div>';const data=await apiGet("/produce/list");allProduce=Array.isArray(data)?data:[];populateLocations();applyFilters();}catch(e){console.error(e);grid.innerHTML=`<div class="col-span-full text-center py-12 text-rose-400 text-sm">${escapeHtml(e.message||"Could not load marketplace")}</div>`;}}
function populateLocations(){const sel=document.getElementById("locationSelect");if(!sel)return;const old=sel.value;const locations=[...new Set(allProduce.map(x=>String(x.location||"").trim()).filter(Boolean))].sort();sel.innerHTML='<option value="">All locations</option>'+locations.map(x=>`<option value="${escapeAttr(x)}">${escapeHtml(x)}</option>`).join("");if(locations.includes(old))sel.value=old;}
function applyFilters(){const q=(document.getElementById("searchInput")?.value||"").trim().toLowerCase(),loc=(document.getElementById("locationSelect")?.value||"").trim(),sort=document.getElementById("sortSelect")?.value||"price_asc";filteredProduce=allProduce.filter(x=>(!q||String(x.crop_name||"").toLowerCase().includes(q))&&(!loc||String(x.location||"")===loc));filteredProduce.sort((a,b)=>{if(sort==="price_desc")return Number(b.expected_price||0)-Number(a.expected_price||0);if(sort==="qty_desc")return Number(b.quantity||0)-Number(a.quantity||0);if(sort==="newest")return Number(b.id||0)-Number(a.id||0);return Number(a.expected_price||0)-Number(b.expected_price||0);});renderMarketplace();}
function renderMarketplace(){const grid=document.getElementById("marketplaceGrid");if(!grid)return;if(!filteredProduce.length){grid.innerHTML='<div class="col-span-full text-center py-12 text-slate-400 text-sm">No matching produce found.</div>';return;}grid.innerHTML=filteredProduce.map(item=>`<article class="bg-slate-800 border border-slate-700 rounded-xl p-5 shadow-xl"><div class="flex justify-between gap-3"><div><h3 class="font-bold text-slate-100">${escapeHtml(item.crop_name)}</h3><p class="text-xs text-slate-400 mt-1">📍 ${escapeHtml(item.location||"Not specified")}</p></div><span class="text-xs text-emerald-400 font-bold">₹${Number(item.expected_price||0).toLocaleString("en-IN")}/Qtl</span></div><div class="grid grid-cols-2 gap-3 my-4 text-xs"><div class="bg-slate-900 rounded-lg p-3"><span class="text-slate-400 block">Available</span><b>${Number(item.quantity||0).toLocaleString("en-IN")} ${escapeHtml(item.unit||"Qtl")}</b></div><div class="bg-slate-900 rounded-lg p-3"><span class="text-slate-400 block">Quality</span><b>${escapeHtml(item.quality_grade||"—")}</b></div></div><div class="flex gap-2"><button onclick="showDetails(${Number(item.id)})" class="flex-1 bg-slate-700 hover:bg-slate-600 rounded-lg py-2 text-xs font-bold">VIEW DETAILS</button><button onclick="openOffer(${Number(item.id)})" class="flex-1 bg-emerald-500 hover:bg-emerald-600 text-slate-950 rounded-lg py-2 text-xs font-bold">MAKE OFFER</button></div><button onclick="buyNow(${Number(item.id)})" class="w-full mt-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg py-2 text-xs font-bold">BUY NOW</button></article>`).join("");}
function showDetails(id){const item=allProduce.find(x=>Number(x.id)===Number(id));if(!item)return;selectedProduce=item;const title=document.getElementById("detailsTitle"),content=document.getElementById("detailsContent");if(title)title.textContent=item.crop_name;if(content)content.innerHTML=`<div class="space-y-3 text-sm"><p><b>Location:</b> ${escapeHtml(item.location||"Not specified")}</p><p><b>Quantity:</b> ${Number(item.quantity||0).toLocaleString("en-IN")} ${escapeHtml(item.unit||"Qtl")}</p><p><b>Quality:</b> ${escapeHtml(item.quality_grade||"—")}</p><p><b>Expected price:</b> ₹${Number(item.expected_price||0).toLocaleString("en-IN")} / Qtl</p><button onclick="openOffer(${Number(item.id)});closeDetailsModal()" class="w-full bg-emerald-500 text-slate-950 font-bold py-2 rounded-lg text-xs">MAKE OFFER</button><button onclick="buyNow(${Number(item.id)});closeDetailsModal()" class="w-full bg-blue-500 text-white font-bold py-2 rounded-lg text-xs">BUY NOW</button></div>`;const modal=document.getElementById("detailsModal");modal?.classList.remove("hidden");modal?.classList.add("flex");}
function closeDetailsModal(){const m=document.getElementById("detailsModal");m?.classList.add("hidden");m?.classList.remove("flex");}
function openOffer(id){selectedProduce=allProduce.find(x=>Number(x.id)===Number(id));if(!selectedProduce)return;document.getElementById("offerCropName").textContent=selectedProduce.crop_name;document.getElementById("offerCropInfo").textContent=`Available: ${selectedProduce.quantity} ${selectedProduce.unit||"Qtl"} • Expected: ₹${Number(selectedProduce.expected_price||0).toLocaleString("en-IN")}/Qtl`;document.getElementById("buyerName").value=getUser()?.name||"";document.getElementById("offerPrice").value="";document.getElementById("offerQuantity").value=Math.min(1,Number(selectedProduce.quantity||0));document.getElementById("offerStatus").textContent="";const m=document.getElementById("offerModal");m?.classList.remove("hidden");m?.classList.add("flex");}
function closeOfferModal(){const m=document.getElementById("offerModal");m?.classList.add("hidden");m?.classList.remove("flex");}
async function submitOffer(e){e.preventDefault();if(!selectedProduce)return;const price=document.getElementById("offerPrice").valueAsNumber,qty=document.getElementById("offerQuantity").valueAsNumber,status=document.getElementById("offerStatus");if(!Number.isFinite(price)||price<=0||!Number.isFinite(qty)||qty<=0||qty>Number(selectedProduce.quantity||0)){status.textContent="Enter a valid offer price and quantity.";status.className="text-xs text-center text-rose-400";return;}try{const data=await apiPost("/offers/place",null,{produce_id:selectedProduce.id,quantity:qty,offered_price:price});status.textContent=data.message||"Offer placed successfully.";status.className="text-xs text-center text-emerald-400";setTimeout(closeOfferModal,700);}catch(err){status.textContent=err.message;status.className="text-xs text-center text-rose-400";}}
async function buyNow(id){const item=allProduce.find(x=>Number(x.id)===Number(id));if(!item)return;const raw=prompt(`Quantity to order (${item.unit||"Qtl"}, max ${item.quantity}):`,Math.min(1,Number(item.quantity||0)));const qty=Number(raw);if(!Number.isFinite(qty)||qty<=0||qty>Number(item.quantity||0)){alert("Invalid quantity.");return;}try{const data=await apiPost("/orders/place",null,{produce_id:item.id,quantity:qty});alert(`Order #${data.order_id} placed. Total: ₹${Number(data.total_price||0).toLocaleString("en-IN")}`);}catch(err){alert(err.message);}}
function loadVoiceSearch(){const params=new URLSearchParams(location.search),q=(params.get("search")||localStorage.getItem("farmDirectVoiceSearch")||"").trim();if(q){const input=document.getElementById("searchInput");if(input){input.value=q;localStorage.removeItem("farmDirectVoiceSearch");}}}
function escapeHtml(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));}
function escapeAttr(x){return escapeHtml(x).replace(/`/g,"&#096;");}
